### ISSUE TITLE
Making prediction on own dataset

### ISSUE THREAD

**Issue by 0xproflupin** [oist/DenseObjectDetection#1]
Hi, I have trained the model on your dataset and wanted to make predictions on my dataset. Can you please tell me what changes I have to do in the predict.py file?

**Comment by iteal** [comment]
Hi! I added two new files for using with a new dataset more easily in : https://github.com/oist/DenseObjectDetection/commit/004ebf3d76bd66fcaa7f13ce3acafbf336927ed5

You can use predict_template.py instead of predict.py to make predictions on your dataset. Just replace the function `predict_data_generator` to load your own images one at a time.
